Correct and document version, when using Holochain release binaries
spartan-holochain-counsel/nix-overlay pull request #3
Opened 2024-12-30 20:32 UTC by pjkundert

Also, added Holochain release 0.5.0-dev.10

2025-01-03 18:36 UTC, pjkundert commented
Hey; I've tested this on Linux x86_64 and aarch64, and Apple aarch64, and it works (the executables are available), and return the correct --version values.

However, the zome-mere-memory tests only seem to work on Linux aarch64; both Linux arm64 and Apple aarch64 appear to "time out" waiting for the Holochain to come up?

2025-01-03 18:51 UTC, pjkundert commented
I updated zome-mere-memory's crates/mere_memory_types/Cargo.toml to hdi 0.5.0 / hdk 0.4.0, and all tests pass on all Linux x86_64 / aarch64 and Apple aarch64 platforms.

I'll do a pull request on zome-mere-memory, @mjbrisebois .

2025-01-09 22:21 UTC, mjbrisebois requested changes

2025-01-09 22:21 UTC, mjbrisebois commented on holochain-overlay/default.nix
> +      version = "0.4.0";  # Holochain release version, not holochain --version
This results in a binary name and version mismatch.
```
$ lair-keystore-0.4.0 --version
lair_keystore 0.5.3
```
We will have to make 2 separate attributes for the release version and the binary suffix.  If the binary suffix is not specified, it defaults to the release version.

2025-01-09 23:03 UTC, pjkundert commented on holochain-overlay/default.nix
> +      version = "0.4.0";  # Holochain release version, not holochain --version
OK, fixed.

2025-01-09 23:08 UTC, mjbrisebois approved these changes

2025-01-09 23:18 UTC, merged